#!/bin/sh
# Render Asterisk config for the Webex Calling sidecar from environment
# variables, then start Asterisk in the foreground.
#
# Unlike the SBC sidecar (one static trunk), Webex needs one SIP
# *registration* per line the customer wants to test from. Lines are
# positional env vars: WEBEX_LINE_1_NUMBER / _SIP_USERNAME / _SIP_PASSWORD,
# WEBEX_LINE_2_..., stopping at the first N with no NUMBER set.
#
# The PJSIP object name for a line is derived from its number
# ("webex-" + E.164 digits). providers/webex_provider.py derives the same
# name from the same env var, so the agent and this container agree
# without any other coupling.
set -eu

TEMPLATES=/etc/asterisk/templates
CONFIG=/etc/asterisk

# ───── Global settings ─────────────────────────────────────────────────────

WEBEX_SIP_DOMAIN="${WEBEX_SIP_DOMAIN:-}"
WEBEX_OUTBOUND_PROXY="${WEBEX_OUTBOUND_PROXY:-$WEBEX_SIP_DOMAIN}"
WEBEX_SIP_PORT="${WEBEX_SIP_PORT:-}"
WEBEX_TLS_VERIFY_SERVER="${WEBEX_TLS_VERIFY_SERVER:-yes}"
WEBEX_CA_BUNDLE="${WEBEX_CA_BUNDLE:-/etc/ssl/certs/ca-certificates.crt}"
WEBEX_EXTERNAL_IP="${WEBEX_EXTERNAL_IP:-}"
WEBEX_LOCAL_NET="${WEBEX_LOCAL_NET:-}"
WEBEX_REG_EXPIRATION="${WEBEX_REG_EXPIRATION:-300}"

if [ -z "$WEBEX_SIP_DOMAIN" ]; then
  echo "ERROR: WEBEX_SIP_DOMAIN is required (the Server / registrar domain shown in Control Hub)." >&2
  exit 1
fi

# Port suffix: empty means "let PJSIP do the _sips._tcp SRV lookup", which
# is what Cisco tells third-party devices to do (Port 0, Transport TLS).
# Set WEBEX_SIP_PORT=5061 if your DNS blocks SRV.
if [ -n "$WEBEX_SIP_PORT" ]; then
  PORT_SUFFIX=":$WEBEX_SIP_PORT"
else
  PORT_SUFFIX=""
fi

# TLS verification against public CAs. Webex's SIP proxies present
# publicly-trusted certificates, so verification should always work; the
# override exists for lab diagnosis only.
if [ "$WEBEX_TLS_VERIFY_SERVER" = "yes" ]; then
  if [ ! -r "$WEBEX_CA_BUNDLE" ]; then
    echo "ERROR: CA bundle $WEBEX_CA_BUNDLE not found; cannot verify Webex TLS." >&2
    echo "       Mount a bundle and set WEBEX_CA_BUNDLE, or (lab only) WEBEX_TLS_VERIFY_SERVER=no." >&2
    exit 1
  fi
  TLS_VERIFY_LINES="verify_server=yes
ca_list_file=$WEBEX_CA_BUNDLE"
else
  echo "WARNING: WEBEX_TLS_VERIFY_SERVER=no — Webex certificate will NOT be verified. Lab use only." >&2
  TLS_VERIFY_LINES="verify_server=no"
fi

# NAT: only emitted when the operator tells us the public IP. Symmetric
# RTP + rport + rewrite_contact (set per endpoint) is enough on most
# networks; this covers hosts where it isn't.
NAT_LINES=""
if [ -n "$WEBEX_EXTERNAL_IP" ]; then
  NAT_LINES="external_media_address=$WEBEX_EXTERNAL_IP
external_signaling_address=$WEBEX_EXTERNAL_IP"
  if [ -n "$WEBEX_LOCAL_NET" ]; then
    NAT_LINES="$NAT_LINES
local_net=$WEBEX_LOCAL_NET"
  fi
fi

# ───── Static templates ────────────────────────────────────────────────────

for tmpl in extensions.conf http.conf modules.conf; do
  cp "$TEMPLATES/$tmpl" "$CONFIG/$tmpl"
done

# ari.conf carries the ARI password. The image has no envsubst, so
# substitute with sed (password is used only as a replacement string;
# escape the characters sed treats specially).
if [ -z "${ARI_PASSWORD:-}" ]; then
  echo "ERROR: ARI_PASSWORD is required." >&2
  exit 1
fi
ari_pw_escaped=$(printf '%s' "$ARI_PASSWORD" | sed -e 's/[\\&|]/\\&/g')
sed -e "s|\${ARI_PASSWORD}|$ari_pw_escaped|g" "$TEMPLATES/ari.conf.tmpl" > "$CONFIG/ari.conf"
chmod 600 "$CONFIG/ari.conf"
chown asterisk:asterisk "$CONFIG/ari.conf" 2>/dev/null || true

cat > "$CONFIG/rtp.conf" <<'EOF'
[general]
rtpstart=10000
rtpend=10999
EOF

# ───── pjsip.conf ──────────────────────────────────────────────────────────

PJSIP="$CONFIG/pjsip.conf"

cat > "$PJSIP" <<EOF
; ───────────────────────────────────────────────────────────────────
; PJSIP configuration for Webex Calling (customer-managed generic SIP
; phone registrations). GENERATED by entrypoint.sh — do not edit; change
; the WEBEX_* variables in .env and restart the container.
; ───────────────────────────────────────────────────────────────────

[global]
type=global
user_agent=Bullseye Agent (Asterisk)
; Webex requires SIP over TLS; there is deliberately no UDP/TCP transport.

[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
method=tlsv1_2
$TLS_VERIFY_LINES
$NAT_LINES

; Inbound calls are not expected — the landing context just hangs up.
EOF

# Asterisk config treats ';' as the start of a comment; a literal one must
# be written as '\;'. Applied to the credential values we emit.
conf_escape() {
  printf '%s' "$1" | sed -e 's/;/\\;/g'
}

# Emit one endpoint/auth/aor/registration set per configured line.
render_line() {
  # $1 = pjsip object name, $2 = number, $3 = SIP username, $4 = SIP password
  # Credentials are passed positionally and emitted with printf %s so shell
  # metacharacters survive intact.
  printf '\n; ───── Line %s ─────\n' "$2" >> "$PJSIP"

  printf '[%s]\ntype=endpoint\n' "$1" >> "$PJSIP"
  printf '%s\n' \
    "transport=transport-tls" \
    "context=from-webex" \
    "disallow=all" \
    "allow=ulaw" \
    "allow=alaw" \
    "direct_media=no" \
    "media_encryption=sdes" \
    "media_encryption_optimistic=no" \
    "rtp_symmetric=yes" \
    "force_rport=yes" \
    "rewrite_contact=yes" \
    "send_pai=no" \
    "trust_id_outbound=no" \
    >> "$PJSIP"
  printf 'from_user=%s\n' "$3" >> "$PJSIP"
  printf 'from_domain=%s\n' "$WEBEX_SIP_DOMAIN" >> "$PJSIP"
  printf 'outbound_proxy=sip:%s%s\\;transport=tls\n' "$WEBEX_OUTBOUND_PROXY" "$PORT_SUFFIX" >> "$PJSIP"
  printf 'outbound_auth=%s-auth\n' "$1" >> "$PJSIP"
  printf 'aors=%s\n\n' "$1" >> "$PJSIP"

  printf '[%s-auth]\ntype=auth\nauth_type=userpass\n' "$1" >> "$PJSIP"
  printf 'username=%s\n' "$3" >> "$PJSIP"
  printf 'password=%s\n\n' "$4" >> "$PJSIP"

  printf '[%s]\ntype=aor\n' "$1" >> "$PJSIP"
  printf 'contact=sip:%s@%s%s\\;transport=tls\n' "$3" "$WEBEX_SIP_DOMAIN" "$PORT_SUFFIX" >> "$PJSIP"
  # No OPTIONS qualify: Webex proxies don't need it and the registration
  # refresh already keeps NAT bindings warm.
  printf 'qualify_frequency=0\n\n' >> "$PJSIP"

  printf '[%s-reg]\ntype=registration\n' "$1" >> "$PJSIP"
  printf '%s\n' \
    "transport=transport-tls" \
    "retry_interval=30" \
    "forbidden_retry_interval=300" \
    "fatal_retry_interval=300" \
    "max_retries=10000" \
    "auth_rejection_permanent=no" \
    "line=yes" \
    >> "$PJSIP"
  printf 'expiration=%s\n' "$WEBEX_REG_EXPIRATION" >> "$PJSIP"
  printf 'outbound_auth=%s-auth\n' "$1" >> "$PJSIP"
  printf 'server_uri=sip:%s%s\\;transport=tls\n' "$WEBEX_SIP_DOMAIN" "$PORT_SUFFIX" >> "$PJSIP"
  printf 'client_uri=sip:%s@%s\n' "$3" "$WEBEX_SIP_DOMAIN" >> "$PJSIP"
  printf 'contact_user=%s\n' "$3" >> "$PJSIP"
  printf 'outbound_proxy=sip:%s%s\\;transport=tls\n' "$WEBEX_OUTBOUND_PROXY" "$PORT_SUFFIX" >> "$PJSIP"
  printf 'endpoint=%s\n' "$1" >> "$PJSIP"
}

count=0
i=1
while :; do
  eval "num=\${WEBEX_LINE_${i}_NUMBER:-}"
  [ -z "$num" ] && break
  eval "user=\${WEBEX_LINE_${i}_SIP_USERNAME:-}"
  eval "pass=\${WEBEX_LINE_${i}_SIP_PASSWORD:-}"
  if [ -z "$user" ] || [ -z "$pass" ]; then
    echo "ERROR: WEBEX_LINE_${i}_NUMBER is set but WEBEX_LINE_${i}_SIP_USERNAME / _SIP_PASSWORD are missing." >&2
    exit 1
  fi
  digits=$(printf '%s' "$num" | tr -cd '0-9')
  # Match providers/webex_provider.py normalisation: 10 digits → assume NANP.
  if [ ${#digits} -eq 10 ]; then
    digits="1$digits"
  fi
  if [ -z "$digits" ]; then
    echo "ERROR: WEBEX_LINE_${i}_NUMBER='$num' contains no digits." >&2
    exit 1
  fi
  name="webex-$digits"
  if grep -q "^\[$name\]" "$PJSIP"; then
    echo "ERROR: duplicate Webex line for +$digits (WEBEX_LINE_${i}_NUMBER)." >&2
    exit 1
  fi
  render_line "$name" "+$digits" "$(conf_escape "$user")" "$(conf_escape "$pass")"
  echo "Configured Webex line $i: +$digits -> $name (SIP user $user)"
  count=$((count + 1))
  i=$((i + 1))
done

if [ "$count" -eq 0 ]; then
  echo "ERROR: no Webex lines configured. Set WEBEX_LINE_1_NUMBER / _SIP_USERNAME / _SIP_PASSWORD." >&2
  exit 1
fi

chmod 600 "$PJSIP"
chown asterisk:asterisk "$PJSIP" 2>/dev/null || true

echo "Rendered config ($count Webex line(s)):"
ls -l "$CONFIG"/*.conf

exec asterisk -f -p -U asterisk -G asterisk
