[modules]
autoload=yes

; Make sure the modules we need are explicitly loaded.
preload => res_pjsip.so
preload => res_pjsip_session.so
load => res_ari.so
load => res_ari_channels.so
load => res_ari_events.so
load => res_http_websocket.so

; Don't bother with chan_sip — chan_pjsip is what we use.
noload => chan_sip.so
